Desarrollo entorno servidor (DSW)/Actividades/C#/UT2/AUT02_03_AfonsoAlejandro/AUT02_03 The Simpsoms/Models/Character.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AUT02_03_The_Simpsoms.Models
{
    public class Character
    {
        public int ID { get; set; }

        [StringLength(15, MinimumLength =3, ErrorMessage = "El nombre tiene que tener entre 3 y 15 caracteres.")]
        [Required(ErrorMessage = "El nombre es obligatorio.")]
        [DisplayName("Nombre")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "La edad es obligatoria.")]
        [Range(0, 100, ErrorMessage = "El valor de edad debe estar entre 0 y 100.")]
        [DisplayName("Edad")]
        public int Age { get; set; }

        [StringLength(15, MinimumLength = 3, ErrorMessage = "El trabajo tiene que tener entre 5 y 20 caracteres.")]
        [Required(ErrorMessage = "Poner su trabajo es obligatorio.")]
        [DisplayName("Trabajo")]
        public string? Job { get; set; }
    }
}

Desarrollo entorno servidor (DSW)/Actividades/C#/UT2/AUT02_03_AfonsoAlejandro/AUT02_03 The Simpsoms/Models/ErrorViewModel.cs
namespace AUT02_03_The_Simpsoms.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Desarrollo entorno servidor (DSW)/Actividades/C#/UT2/AUT02_03_AfonsoAlejandro/AUT02_03 The Simpsoms/Controllers/SimpsonsController.cs
using AUT02_03_The_Simpsoms.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Immutable;
using System.Diagnostics;

namespace AUT02_03_The_Simpsoms.Controllers
{
    public class SimpsonsController : Controller
    {

        static int currentId = 3;
        static List<Character> simpsonsCharacters = new List<Character>
        {
            new Character { ID = 1, Name = "Homer Simpson", Age = 40, Job = "Planta Nuclear" },
            new Character { ID = 2, Name = "Marge Simpson", Age = 38, Job = "Ama de casa" }
        };

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CharacterList()
        {
            return View(simpsonsCharacters);
        }

        public IActionResult CharacterDetails(int ID)
        {
            Character character = simpsonsCharacters.SingleOrDefault(c => c.ID == ID);
            if (character == null)
            {
                return View("Error");
            }
            return View(character);
        }

        [HttpGet]
        public IActionResult CharacterCreation()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CharacterCreation(Character character)
        {
            if (ModelState.IsValid)
            {
                character.ID = currentId++;
                simpsonsCharacters.Add(character);
                return RedirectToAction("CharacterList");
            }
            return View(character);
        }

        [HttpGet]
        public IActionResult CharacterEdit(int ID)
        {
            Character character = simpsonsCharacters.SingleOrDefault(c => c.ID == ID);
            if (character == null)
            {
                return View("Error");
            }
            return View(character);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CharacterEdit(Character editedCharacter)
        {
            if (ModelState.IsValid)
            {
                Character characterToUpdate = simpsonsCharacters.FirstOrDefault(c => c.ID == editedCharacter.ID);
                if (characterToUpdate != null)
                {
                    characterToUpdate.Name = editedCharacter.Name;
                    characterToUpdate.Age = editedCharacter.Age;
                    characterToUpdate.Job = editedCharacter.Job;
                }
                else
                {
                    return View("Error");
                }
                return RedirectToAction("CharacterList");
            }
            return View(editedCharacter);
        }

        public IActionResult CharacterDelete(int ID)
        {
            Character character = simpsonsCharacters.SingleOrDefault(c => c.ID == ID);
            simpsonsCharacters.Remove(character);
            return RedirectToAction("CharacterList");
        }
    }
}

Desarrollo entorno servidor (DSW)/Actividades/C#/UT2/AUT02_03_AfonsoAlejandro/AUT02_03 The Simpsoms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AUT02_03_The_Simpsoms</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AUT02_03_The_Simpsoms.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AUT02_03_The_Simpsoms</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Simpsons" asp-action="Index">The Simpsons MVC</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Simpsons" asp-action="CharacterList">Listado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Simpsons" asp-action="CharacterCreation">Crear Personaje</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AUT02_03_The_Simpsoms - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>